nameOverride: "microservice"

replicaCount: 1

image:
  repository: circleguard/service
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 8080

env:

  SPRING_PROFILES_ACTIVE: docker

  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/circleguard
  SPRING_DATASOURCE_USERNAME: admin
  SPRING_DATASOURCE_PASSWORD: password

  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

  SPRING_NEO4J_URI: bolt://neo4j:7687
  SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: password

  SPRING_DATA_REDIS_HOST: redis

resources:
  limits:
    cpu: 500m
    memory: 512Mi