# Generales del Microservicio
nameOverride: "microservice-name"
replicaCount: 1

image:
  repository: circleguard/servicio # Sobreescribir en Jenkins
  pullPolicy: IfNotPresent
  tag: "latest" # Jenkins inyectará el Build ID

service:
  type: ClusterIP
  port: 8080 # Puerto interno del contenedor

# Variables de Configuración que Spring Boot leerá
env:
  SPRING_PROFILES_ACTIVE: "stage" # dev, stage, master
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/db_name"
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "password"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  NEO4J_URI: "bolt://neo4j-service:7687"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "password"
  REDIS_HOST: "redis-service"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi