apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.nameOverride }}
    spec:
      containers:
        - name: {{ .Values.nameOverride }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL | quote }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME | quote }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD | quote }}
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
            - name: NEO4J_URI
              value: {{ .Values.env.NEO4J_URI | quote }}
            - name: NEO4J_USERNAME
              value: {{ .Values.env.NEO4J_USERNAME | quote }}
            - name: NEO4J_PASSWORD
              value: {{ .Values.env.NEO4J_PASSWORD | quote }}
            - name: REDIS_HOST
              value: {{ .Values.env.REDIS_HOST | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}